### ISSUE TITLE
CIC name in dashboard is the "type" column exploded out

### ISSUE THREAD

**Issue by Fryguy** [ManageIQ/manageiq-providers-ibm_cic#25]
![Fullscreen_11_30_22__4_12_PM](https://user-images.githubusercontent.com/52120/204909762-bcfe6819-6bf8-44e4-a084-edeffc9e3acf.png)

This might also be present on other "new" providers.  I checked Amazon and that looked ok.  I'm not exactly sure where to fix this, so opening a bug.

**Comment by agrare** [comment]
I actually don't know where this is coming from either, @jeffibm do you know?

**Comment by jeffibm** [comment]
> I actually don't know where this is coming from either, @jeffibm do you know?

No, but let's find out..

**Comment by Fryguy** [comment]
This is still an issue.

**Comment by DavidResende0** [comment]
Looks like this is an issue for the VPC provider as well
<img width="447" alt="Screenshot 2023-05-23 at 10 41 49 AM" src="https://github.com/ManageIQ/manageiq-providers-ibm_cic/assets/64800041/b15f0193-50ec-4bbb-9866-8bccebd544a7">

**Comment by jeffibm** [comment]
Debugging - 

For this particular tooltip- `ManageIQ/Providers/Google/Cloud Manager` is being rendered from [Quaditem.jsx#L60](https://github.com/ManageIQ/manageiq-ui-classic/blob/4bc4fdf35295d1811c1b4e5d2e8b88d5ac37ef41/app/javascript/components/quadicon/Quaditem.jsx#L60) 
<img width="327" alt="image" src="https://github.com/ManageIQ/manageiq-providers-ibm_cic/assets/87487049/8beb215b-7508-4508-a418-55365caf9458">

We get the data from a request `/ems_cloud_dashboard/aggregate_status_data/17`
<img width="1040" alt="image" src="https://github.com/ManageIQ/manageiq-providers-ibm_cic/assets/87487049/be6ccdf1-085b-4101-bd20-7be1d23124c1">

(The `aggregate_status_data` method is available in other controllers as well, which looks the same)

**Comment by Fryguy** [comment]
That leads to the quadicon_hash method which is here: https://github.com/ManageIQ/manageiq-decorators/blob/master/app/helpers/quadicon_helper.rb

**Comment by akhilkr128** [comment]
From the `quadicon_hash` method execution will move to the corresponding decorator function. Like here https://github.com/ManageIQ/manageiq-decorators/blob/d32a9713e7e780519c4252607740a7879f8c56eb/app/decorators/manageiq/providers/cloud_manager_decorator.rb#L26. The `ui_lookup` will look for a key in the `locale/en.yml` file. I have added a key for google cloud provider as `ManageIQ::Providers::Google::CloudManager: Google` it gave me the below results.
<img width="706" alt="Screenshot 2023-06-14 at 4 34 26 PM" src="https://github.com/ManageIQ/manageiq-providers-ibm_cic/assets/16753936/d8a9a016-c475-4dca-af49-609e5f39fc45">

Any other suggestions for this issue?
@jeffibm, @Fryguy, @agrare

**Comment by akhilkr128** [comment]
PR Created- https://github.com/ManageIQ/manageiq/pull/22572
